# Generated by Django 4.1.7 on 2023-03-28 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSeller', models.CharField(max_length=50)),
                ('lastNameSeller', models.CharField(max_length=50)),
                ('registerDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProduct', models.CharField(max_length=50)),
                ('priceProduct', models.CharField(max_length=50)),
                ('dateReleased', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default='false')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.category')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.sellers')),
            ],
        ),
    ]
