# Generated by Django 4.1.7 on 2023-04-04 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_remove_transacts_category_remove_transacts_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameBuyer', models.CharField(max_length=50)),
                ('lastNameBuyer', models.CharField(max_length=50)),
                ('dateRegister', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='transacts',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transacts',
            name='dateTransact',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='transacts',
            name='buyers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.buyers'),
        ),
    ]
